### ISSUE TITLE
cpu占用率居高不下

### ISSUE THREAD

**Issue by robinhe26** [glzjin/ss-panel-v3-mod#142]
5971 root       20   0 2878M  312M 16092 S 99.0 15.6 25h06:31 java -jar ssshell.jar                                                                 
 6000 root       20   0 2878M  312M 16092 R 97.0 15.6 24h32:30 java -jar ssshell.jar

ssshell打开后cpu跑满，用就是jstack查了下：
root@iaJ76G:~/ssshell# jstack 23401|grep 5b89 -A 30
"Thread-2" #15 prio=5 os_prio=0 tid=0x00007f7244566800 nid=0x5b89 runnable [0x00007f72173c6000]
   java.lang.Thread.State: RUNNABLE
        at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
        at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4801)
        at java.util.regex.Pattern$Prolog.match(Pattern.java:4741)
        at java.util.regex.Pattern$Begin.match(Pattern.java:3525)
        at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
        at java.util.regex.Pattern$Start.match(Pattern.java:3461)
        at java.util.regex.Matcher.search(Matcher.java:1248)
        at java.util.regex.Matcher.find(Matcher.java:637)
        at Shadowsocks_Shell.Main.getIP6Address(Main.java:1399)
        at Shadowsocks_Shell.Main.ReadLocalDeny(Main.java:1131)
        at Shadowsocks_Shell.Main$3.run(Main.java:372)

这个是在匹配ipv6地址的时候卡住了吗？我的主机没有ipv6地址，是这个问题吗？多谢！

**Comment by robinhe26** [comment]
实际测试关闭云安全  cloudsafe 就好了，应该是ipv6的问题
