### ISSUE TITLE
无法统计非本机流量

### ISSUE THREAD

**Issue by shenlw** [glzjin/ss-panel-v3-mod#188]
可以连接，但是无法显示远程的用户连接数和流量统计
使用glzjin/shadowsocks的程序
下面是userapiconfig.py的配置
```
# Config
NODE_ID = 4


#hour,set 0 to disable
SPEEDTEST = 6
CLOUDSAFE = 1
ANTISSATTACK = 0
AUTOEXEC = 0
MULTI_THREAD = 0

SERVER_PUB_ADDR = '127.0.0.1' # mujson_mgr need this to generate ssr link
API_INTERFACE = 'glzjinmod' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)

#mudb
MUDB_FILE = 'mudb.json'

# Mysql
MYSQL_HOST = '64.137.174.xxx'
MYSQL_PORT = 3306
MYSQL_USER = 'xxxx'
MYSQL_PASS = 'xxx'
MYSQL_DB = 'xxxxx'
MYSQL_UPDATE_TIME = 60

MYSQL_SSL_ENABLE = 0
MYSQL_SSL_CA = ''
MYSQL_SSL_CERT = ''
MYSQL_SSL_KEY = ''

# API
API_HOST = 'https://ss.lingyue.ml'
API_PORT = 443
API_PATH = '/mu/v2/'
API_TOKEN = 'xxxxxx'
API_UPDATE_TIME = 60

# Manager (ignore this)
MANAGE_PASS = 'ss233333333'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 23333
```
网站： [https://ss.lingyue.ml](https://ss.lingyue.ml)

**Comment by sunnoy** [comment]
可以请问一下你的邮箱设置么，smtp该怎么设置呢

**Comment by shenlw66** [comment]
smtp 的问题你可以自己去 issue 里面搜索有没有相关回答，或者新开一个 issue

**Comment by glzjin** [comment]
后端日志能发一下吗

**Comment by shenlw** [comment]
```
INFO: loading config from user-config.json
Exception in thread autoblock:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/shadowsocks/auto_block.py", line 39, in auto_block_thread
    start_line = file_len("/etc/hosts.deny")
  File "/root/shadowsocks/auto_block.py", line 33, in file_len
    return i + 1
UnboundLocalError: local variable 'i' referenced before assignment

INFO: loading config from user-config.json
Exception in thread autoblock:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/shadowsocks/auto_block.py", line 39, in auto_block_thread
    start_line = file_len("/etc/hosts.deny")
  File "/root/shadowsocks/auto_block.py", line 33, in file_len
    return i + 1
UnboundLocalError: local variable 'i' referenced before assignment

2016-08-27 23:12:47 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-08-27 23:12:48 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-08-27 23:12:49 INFO     db_transfer.py:411 db start server at port [10025] pass [xxxxxx] protocol [auth_sha1_v2_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-08-27 23:12:49 INFO     server_pool.py:137 starting server at [::]:10025
2016-08-27 23:12:49 INFO     server_pool.py:163 starting server at 0.0.0.0:10025
2016-08-27 23:12:49 INFO     db_transfer.py:411 db start server at port [13018] pass [xxxxxx] protocol [origin] obfs [plain]
2016-08-27 23:12:49 INFO     server_pool.py:137 starting server at [::]:13018
2016-08-27 23:12:49 INFO     server_pool.py:163 starting server at 0.0.0.0:13018
2016-08-27 23:12:49 INFO     db_transfer.py:411 db start server at port [48095] pass [xxxxxx] protocol [origin] obfs [plain]
2016-08-27 23:12:49 INFO     server_pool.py:137 starting server at [::]:48095
```

**Comment by WhoRUa** [comment]
能问一下你的支付接口怎么做的吗

**Comment by WhoRUa** [comment]
有教程链接也好

**Comment by shenlw** [comment]
？？？我没有弄支付接口啊...
