### ISSUE TITLE
后端报错，连不上

### ISSUE THREAD

**Issue by shenlw** [glzjin/ss-panel-v3-mod#208]
```
2016-09-01 04:43:06 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-09-01 04:43:06 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-09-01 04:43:12 ERROR    db_transfer.py:545 Traceback (most recent call last):
  File "/root/libsodium-1.0.10/shadowsocks/db_transfer.py", line 538, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/libsodium-1.0.10/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.7/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.7/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'is_multi_user' in 'field list'")
```
按照教程一步步来的

**Comment by shenlw** [comment]
应该是要更新前端

**Comment by HavenLiu** [comment]
我也遇到这个问题，请问是更新哪个前端？有没有更新教程

**Comment by shenlw** [comment]
@HavenLiu https://github.com/glzjin/shadowsocks/wiki/%E8%AF%B4%E6%98%8E%E4%BB%A5%E5%8F%8A%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

> 关于升级
> cd shadowsocks
> git pull
> 记得看 https://github.com/glzjin/shadowsocks/wiki/重大更新日志 添加配置项。
