### ISSUE TITLE
更换数据库后，所有节点显示离线但是不影响使用。

### ISSUE THREAD

**Issue by rainlgtao** [glzjin/ss-panel-v3-mod#248]
![image](https://cloud.githubusercontent.com/assets/20722752/18941733/0b314060-8646-11e6-8a79-fbd66d9c96ba.png)
备用站点就显示正常。
![image](https://cloud.githubusercontent.com/assets/20722752/18942349/f1878426-864a-11e6-9034-18fee298c163.png)

更换数据库后，所有节点显示离线但是不影响使用。
用备用站点连接同一数据库就显示在线。
请问赵老师是什么问题？谢谢！

**Comment by glzjin** [comment]
@rainlgtao 能发其中某个节点的后端日志吗？

**Comment by rainlgtao** [comment]
2016-09-29 14:18:08 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:18:08 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:30316 via port 10000
2016-09-29 14:18:09 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:18:09 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:30823 via port 10000
2016-09-29 14:19:07 INFO     auto_block.py:59 Read hosts.deny from line 141027
2016-09-29 14:19:10 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:19:10 ERROR    tcprelay.py:971 when connect to 191.234.20.241:443 from ::ffff:111.85.22.213:30985 via port 10000
2016-09-29 14:20:07 INFO     auto_block.py:59 Read hosts.deny from line 141029
2016-09-29 14:20:09 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:20:09 ERROR    tcprelay.py:971 when connect to 40.115.1.44:443 from ::ffff:111.85.22.213:30259 via port 10000
2016-09-29 14:21:08 INFO     auto_block.py:59 Read hosts.deny from line 141031
2016-09-29 14:22:08 INFO     auto_block.py:59 Read hosts.deny from line 141033
2016-09-29 14:23:08 INFO     auto_block.py:59 Read hosts.deny from line 141035
2016-09-29 14:24:08 INFO     auto_block.py:59 Read hosts.deny from line 141037
2016-09-29 14:25:08 INFO     auto_block.py:59 Read hosts.deny from line 141039
2016-09-29 14:25:54 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:25:54 ERROR    tcprelay.py:971 when connect to 69.28.58.54:80 from ::ffff:111.85.22.213:30524 via port 10000
2016-09-29 14:25:55 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:25:55 ERROR    tcprelay.py:971 when connect to 65.255.35.150:80 from ::ffff:111.85.22.213:30942 via port 10000
2016-09-29 14:25:55 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:25:55 ERROR    tcprelay.py:971 when connect to 65.255.35.142:80 from ::ffff:111.85.22.213:31089 via port 10000
2016-09-29 14:25:55 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:25:55 ERROR    tcprelay.py:971 when connect to 69.28.58.55:80 from ::ffff:111.85.22.213:30675 via port 10000
2016-09-29 14:25:55 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:25:55 ERROR    tcprelay.py:971 when connect to 65.255.35.144:80 from ::ffff:111.85.22.213:30825 via port 10000
2016-09-29 14:25:56 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:25:56 ERROR    tcprelay.py:971 when connect to 65.255.35.143:80 from ::ffff:111.85.22.213:30411 via port 10000
2016-09-29 14:26:08 INFO     auto_block.py:59 Read hosts.deny from line 141041
2016-09-29 14:27:09 INFO     auto_block.py:59 Read hosts.deny from line 141043
2016-09-29 14:27:09 ERROR    speedtest_thread.py:121 Speedtest error
2016-09-29 14:28:09 INFO     auto_block.py:59 Read hosts.deny from line 141045
2016-09-29 14:28:41 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:28:41 ERROR    tcprelay.py:971 when connect to 69.28.58.54:80 from ::ffff:111.85.22.213:30475 via port 10000
2016-09-29 14:28:41 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:28:41 ERROR    tcprelay.py:971 when connect to 65.255.35.150:80 from ::ffff:111.85.22.213:31017 via port 10000
2016-09-29 14:28:41 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:28:41 ERROR    tcprelay.py:971 when connect to 65.255.35.142:80 from ::ffff:111.85.22.213:31158 via port 10000
2016-09-29 14:28:41 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:28:41 ERROR    tcprelay.py:971 when connect to 69.28.58.55:80 from ::ffff:111.85.22.213:30612 via port 10000
2016-09-29 14:28:42 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:28:42 ERROR    tcprelay.py:971 when connect to 65.255.35.144:80 from ::ffff:111.85.22.213:30878 via port 10000
2016-09-29 14:28:42 ERROR    tcprelay.py:969 [Errno 111] Connection refused
2016-09-29 14:28:42 ERROR    tcprelay.py:971 when connect to 65.255.35.143:80 from ::ffff:111.85.22.213:30332 via port 10000
2016-09-29 14:29:09 INFO     auto_block.py:59 Read hosts.deny from line 141047
2016-09-29 14:30:09 INFO     auto_block.py:59 Read hosts.deny from line 141049
2016-09-29 14:31:09 INFO     auto_block.py:59 Read hosts.deny from line 141051
2016-09-29 14:32:09 INFO     auto_block.py:59 Read hosts.deny from line 141053
2016-09-29 14:33:10 INFO     auto_block.py:59 Read hosts.deny from line 141055
2016-09-29 14:34:11 INFO     auto_block.py:59 Read hosts.deny from line 141057
2016-09-29 14:35:12 INFO     auto_block.py:59 Read hosts.deny from line 141059
2016-09-29 14:36:13 INFO     auto_block.py:59 Read hosts.deny from line 141061
2016-09-29 14:36:51 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:36:51 ERROR    tcprelay.py:971 when connect to 134.170.105.48:443 from ::ffff:111.85.22.213:30982 via port 10000
2016-09-29 14:37:13 INFO     auto_block.py:59 Read hosts.deny from line 141063
2016-09-29 14:38:14 INFO     auto_block.py:59 Read hosts.deny from line 141065
2016-09-29 14:39:09 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:39:09 ERROR    tcprelay.py:971 when connect to 40.115.1.44:443 from ::ffff:111.85.22.213:30334 via port 10000
2016-09-29 14:39:15 INFO     auto_block.py:59 Read hosts.deny from line 141067
2016-09-29 14:40:16 INFO     auto_block.py:59 Read hosts.deny from line 141069
2016-09-29 14:41:16 INFO     auto_block.py:59 Read hosts.deny from line 141071
2016-09-29 14:42:17 INFO     auto_block.py:59 Read hosts.deny from line 141073
2016-09-29 14:43:18 INFO     auto_block.py:59 Read hosts.deny from line 141075
2016-09-29 14:44:12 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:44:12 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:30304 via port 10000
2016-09-29 14:44:17 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:44:17 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:31058 via port 10000
2016-09-29 14:44:19 INFO     auto_block.py:59 Read hosts.deny from line 141077
2016-09-29 14:44:29 ERROR    db_transfer.py:553 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 546, in thread_db
    while True:
  File "/root/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

2016-09-29 14:45:20 INFO     auto_block.py:59 Read hosts.deny from line 141079
2016-09-29 14:45:49 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:45:49 ERROR    tcprelay.py:971 when connect to 191.234.20.241:443 from ::ffff:111.85.22.213:31032 via port 10000
2016-09-29 14:46:03 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:46:03 ERROR    tcprelay.py:971 when connect to 40.115.1.44:443 from ::ffff:111.85.22.213:30496 via port 10000
2016-09-29 14:46:20 INFO     auto_block.py:59 Read hosts.deny from line 141081
2016-09-29 14:47:09 INFO     tcprelay.py:1202 port 10000 connections up to 25
2016-09-29 14:47:22 INFO     auto_block.py:59 Read hosts.deny from line 141083
2016-09-29 14:48:14 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:48:14 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:31191 via port 10000
2016-09-29 14:48:14 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:48:14 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:30388 via port 10000
2016-09-29 14:48:18 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:48:18 ERROR    tcprelay.py:971 when connect to 13.107.3.128:443 from ::ffff:111.85.22.213:30522 via port 10000
2016-09-29 14:48:23 INFO     auto_block.py:59 Read hosts.deny from line 141085
2016-09-29 14:49:17 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:49:17 ERROR    tcprelay.py:971 when connect to 191.234.20.241:443 from ::ffff:111.85.22.213:30528 via port 10000
2016-09-29 14:49:24 INFO     auto_block.py:59 Read hosts.deny from line 141087
2016-09-29 14:50:07 ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
2016-09-29 14:50:07 ERROR    tcprelay.py:971 when connect to 40.115.1.44:443 from ::ffff:111.85.22.213:30946 via port 10000
2016-09-29 14:50:24 INFO     auto_block.py:59 Read hosts.deny from line 141089
2016-09-29 14:51:26 INFO     auto_block.py:59 Read hosts.deny from line 141091
2016-09-29 14:51:47 ERROR    db_transfer.py:553 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 546, in thread_db
    while True:
  File "/root/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

2016-09-29 14:52:26 INFO     auto_block.py:59 Read hosts.deny from line 141093
2016-09-29 14:53:27 INFO     auto_block.py:59 Read hosts.deny from line 141095
2016-09-29 14:53:49 ERROR    db_transfer.py:553 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 546, in thread_db
    while True:
  File "/root/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

2016-09-29 14:54:28 INFO     auto_block.py:59 Read hosts.deny from line 141097
2016-09-29 14:55:29 INFO     auto_block.py:59 Read hosts.deny from line 141099
2016-09-29 14:56:29 INFO     auto_block.py:59 Read hosts.deny from line 141101
2016-09-29 14:57:30 INFO     auto_block.py:59 Read hosts.deny from line 141103
2016-09-29 14:58:31 INFO     auto_block.py:59 Read hosts.deny from line 141105
2016-09-29 14:59:00 ERROR    db_transfer.py:553 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 546, in thread_db
    while True:
  File "/root/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

2016-09-29 14:59:34 INFO     auto_block.py:59 Read hosts.deny from line 141107
2016-09-29 15:00:39 INFO     auto_block.py:59 Read hosts.deny from line 141109
2016-09-29 15:01:40 INFO     auto_block.py:59 Read hosts.deny from line 141111

**Comment by glzjin** [comment]
请自己检查数据库设置 从主数据库的错误日志入手。

**Comment by rainlgtao** [comment]
@glzjin 但是用备用站点连上后又是正常的。应该是数据库跟主站点有冲突？

**Comment by glzjin** [comment]
@rainlgtao 不是，你看节点后端上的日志就知道了，超时错误了。

**Comment by rainlgtao** [comment]
@glzjin 找老师

**Comment by rainlgtao** [comment]
@glzjin 赵老师
# Time: 160930  1:40:10
# User@Host: lgt[lgt] @  [192.210.241.***]  Id: 13084
# Query_time: 79.140554  Lock_time: 0.000148 Rows_sent: 678  Rows_examined: 703
SET timestamp=1475170810;
SELECT id,port,u,d,transfer_enable,passwd,enable,method,obfs,obfs_param,protocol,protocol_param,id,node_speedlimit,forbidden_ip,forbidden_port,disconnect_ip,is_multi_user FROM user WHERE `class`>=0  AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`;
# Time: 160930  3:09:59
# User@Host: lgt[lgt] @  [104.224.179.***]  Id: 15178
# Query_time: 14.078342  Lock_time: 0.000129 Rows_sent: 678  Rows_examined: 703
SET timestamp=1475176199;
SELECT port,u,d,transfer_enable,passwd,enable,method,obfs,obfs_param,protocol,protocol_param,id,node_speedlimit,forbidden_ip,forbidden_port,disconnect_ip FROM user WHERE `class`>=0  AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`;

帮忙看下数据库日志有问题吗？

**Comment by rainlgtao** [comment]
谢谢赵老师，问题解决了，有一个服务器的时间不对，还是赵老师厉害。
