### ISSUE TITLE
新节点会运行一晚上后报错

### ISSUE THREAD

**Issue by terryops** [glzjin/ss-panel-v3-mod#252]
首先是这个
>ERROR    db_transfer.py:557 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 549, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 101, in update_all_user
    cur.execute("INSERT INTO `ss_node_info` (`id`, `node_id`, `uptime`, `load`, `log_time`) VALUES (NULL, '" + str(get_config().NODE_ID) + "', '" + str(self.uptime()) + "', '" + str(self.load()) + "', unix_timestamp()); ")
  File "/root/shadowsocks/db_transfer.py", line 172, in uptime
    with open('/proc/uptime', 'r') as f:
IOError: [Errno 24] Too many open files: '/proc/uptime'

然后连接的时候会出现：
>tcprelay.py:123 creater encryptor fail at port 1333

**Comment by glzjin** [comment]
请按照安装说明进行优化。
