### ISSUE TITLE
装面板的机器上运行后端时报错

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#255]
[root@a shadowsocks]# python server.py
IPv6 support
Traceback (most recent call last):
  File "server.py", line 30, in <module>
    import auto_thread
  File "/root/shadowsocks/auto_thread.py", line 10, in <module>
    import gnupg
  File "/root/shadowsocks/gnupg/__init__.py", line 23, in <module>
    from . import gnupg
  File "/root/shadowsocks/gnupg/gnupg.py", line 42, in <module>
    from ._meta    import GPGBase
  File "/root/shadowsocks/gnupg/_meta.py", line 47, in <module>
    from . import _parsers
  File "/root/shadowsocks/gnupg/_parsers.py", line 30, in <module>
    from ordereddict import OrderedDict
ImportError: No module named ordereddict
从来没有遇到过这种错误，不知道是怎么回事

**Comment by glzjin** [comment]
@leosejin pip install orderedditct 缺啥补啥 吃嘛嘛香
