### ISSUE TITLE
后端连接不上

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#277]
[root@5m-Trial shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-10-04 03:32:32 WARNING  _util.py:685 Ignoring '/usr/bin/gpg' (path is a symlink)
2016-10-04 03:32:32 ERROR    _util.py:422 Could not find binary for 'gpg'.
2016-10-04 03:32:32 INFO     _meta.py:432 Setting homedir to '/root/.config/python-gnupg'
2016-10-04 03:32:32 INFO     gnupg.py:150 
Initialised settings:
binary: /usr/bin/gpg2
binary version: 2.0.14
homedir: /root/.config/python-gnupg
ignore_homedir_permissions: False
keyring: /root/.config/python-gnupg/pubring.gpg
secring: /root/.config/python-gnupg/secring.gpg
default_preference_list: SHA512 SHA384 SHA256 AES256 CAMELLIA256 TWOFISH AES192 ZLIB ZIP Uncompressed
keyserver: hkp://wwwkeys.pgp.net
options: None
verbose: False
use_agent: False

Exception in thread autoexec:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/shadowsocks/auto_thread.py", line 32, in auto_thread
    key_data = open('ssshell.asc').read()
IOError: [Errno 2] No such file or directory: 'ssshell.asc'

2016-10-04 03:32:32 INFO     util.py:85 loading libcrypto from libcrypto.so.10
Shadowsocks 
2016-10-04 03:32:32 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
到这里就没有下文了，载入不了用户的端口

**Comment by glzjin** [comment]
@leosejin 你节点id不对

**Comment by leosejin** [comment]
确实ID的问题，不过我是在 面板添加节点前 先去后端运行的，所以ID对不上。在面板加了节点地址再去后端运行就正常了。
谢谢赵辅导员
