### ISSUE TITLE
添加新节点出现错误,试着用issues中的方法没解决

### ISSUE THREAD

**Issue by laoyu1120** [glzjin/ss-panel-v3-mod#280]
安装步骤和配置和以前添加的节点一样,开启服务的时候,提示下边的错误码
试过用https://github.com/glzjin/ss-panel-v3-mod/issues/190这个方法没成功
在破娃酱的github上也找了一圈,也没解决.
数据库配置正确 防火墙也关闭了,3306端口也是开放的,其它服务器都可以连接
python版本是2.6.6.
 libsodium版本是1.0.11拜托.先谢过了
ERROR    db_transfer.py:557 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 550, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 256, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'is_multi_user' in 'field list'")

**Comment by Jouaoo** [comment]
前端版本过低

**Comment by glzjin** [comment]
@laoyu1120 就不能按照说明升级到最新版吗没。。。

**Comment by laoyu1120** [comment]
抱歉我又来了,更新前端以后,开启shadowsocks服务提示这个.
INFO     server_pool.py:139 starting server at [::]:10000
2016-10-05 12:22:30 WARNING  common.py:306 You did't specify CIDR routing prefix size for 123.190.92.179, implicit treated as 123.190.92.179/32
2016-10-05 12:22:30 WARNING  common.py:306 You did't specify CIDR routing prefix size for 42.248.48.63, implicit treated as 42.248.48.63/32
2016-10-05 12:22:30 WARNING  common.py:306 You did't specify CIDR routing prefix size for 123.190.92.179, implicit treated as 123.190.92.179/32
2016-10-05 12:22:30 WARNING  server_pool.py:152 IPV6 [Errno 98] Address already in use
2016-10-05 12:22:30 INFO     server_pool.py:165 starting server at 0.0.0.0:10000
2016-10-05 12:22:30 WARNING  common.py:306 You did't specify CIDR routing prefix size for 123.190.92.179, implicit treated as 123.190.92.179/32
2016-10-05 12:22:30 WARNING  common.py:306 You did't specify CIDR routing prefix size for 42.248.48.63, implicit treated as 42.248.48.63/32
2016-10-05 12:22:30 WARNING  common.py:306 You did't specify CIDR routing prefix size for 123.190.92.179, implicit treated as 123.190.92.179/32
2016-10-05 12:22:30 WARNING  server_pool.py:177 IPV4 [Errno 98] Address already in use

**Comment by glzjin** [comment]
@laoyu1120 你重复运行了多个服务端

**Comment by A1exLiu** [comment]
IP地址露出来了……建议修改

**Comment by Jouaoo** [comment]
ddcc大军已经出发

**Comment by glzjin** [comment]
@Jouaoo 已经拉黑，请不要在我这里讨论网络暴力。

**Comment by laoyu1120** [comment]
刚刚把vps重做 了系统.然后通过运行一次./logrun.sh来启动服务还是报错误代码
 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as 
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as 
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for, implicit treated as
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as 
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as 
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as 
2016-10-05 13:57:43 INFO     server_pool.py:165 starting server at 0.0.0.0:10000
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as 
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as
2016-10-05 13:57:43 WARNING  common.py:306 You did't specify CIDR routing prefix                                                                                              size for , implicit treated as

**Comment by kaikaisd** [comment]
@laoyu1120 看wiki 教程最低的那個u什麼的指令 如果沒有記錯的話

**Comment by laoyu1120** [comment]
你指的是这个吗?
7.我们优化下

编辑 /etc/security/limits.conf

最后添加

* soft nofile 51200

* hard nofile 51200
然后在运行之前执行

ulimit -n 51200

**Comment by kaikaisd** [comment]
@laoyu1120 對

**Comment by glzjin** [comment]
@laoyu1120

**Comment by glzjin** [comment]
@laoyu1120 错，那不是报错。

**Comment by laoyu1120** [comment]
感谢各位,问题已经解决了.果然是楼上说的那个问题
7.我们优化下

编辑 /etc/security/limits.conf

最后添加

* soft nofile 51200

* hard nofile 51200
然后在运行之前执行

ulimit -n 51200
因为之前的服务器,没优化就能直接连接,所以就没想到是这个问题.
在这里给后边的兄弟提醒一下,安装完第6步以后运行:
netstat -ltnap | grep -c CLOSE_WAIT
显示的数值很大（超过50是严重不正常）那就必须要按照第7步优化
还是建议优化.再次感谢各位的解答

**Comment by glzjin** [comment]
@laoyu1120 你的日志你并没有体现出这个问题= =但是= =优化无论什么情况下 都应该做一下，这里也说一下，没有完整的照着安装说明走，出了问题= =请先自己解决。话放在这里以示后来。
