### ISSUE TITLE
重启主服务器后节点列表除了主服务器外全部红色感叹号

### ISSUE THREAD

**Issue by EwSan** [glzjin/ss-panel-v3-mod#284]
重启主服务器后节点列表除了主服务器外全部红色感叹号，但是SSR客户端可以正常连接。
另外问下开启debug后日志保存在哪里的。

**Comment by Woophp** [comment]
浏览器F12抓包

**Comment by glzjin** [comment]
@EwSan 请发后端日志

**Comment by EwSan** [comment]
@glzjin 是主服务器的后端日志吗

**Comment by glzjin** [comment]
@EwSan 子节点的

**Comment by EwSan** [comment]
[root@iZj6c0vmnn5rfhklrm2dhjZ shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 not support
INFO: loading config from user-config.json
2016-10-05 15:23:59 INFO     util.py:85 loading libcrypto from libcrypto.so.10
Shadowsocks 
2016-10-05 15:23:59 INFO     asyncdns.py:324 dns server: [('10.143.22.118', 53), ('10.143.22.116', 53)]

**Comment by EwSan** [comment]
[root@iZj6c0vmnn5rfhklrm2dhjZ shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 not support
INFO: loading config from user-config.json
2016-10-05 15:23:59 INFO     util.py:85 loading libcrypto from libcrypto.so.10
Shadowsocks 
2016-10-05 15:23:59 INFO     asyncdns.py:324 dns server: [('10.143.22.118', 53), ('10.143.22.116', 53)]
2016-10-05 15:25:02 ERROR    db_transfer.py:557 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 549, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '23.106.152.201' (110)")

2016-10-05 15:26:02 ERROR    auto_block.py:185 Auto block thread error

**Comment by glzjin** [comment]
@EwSan 数据库无法连接

**Comment by EwSan** [comment]
谢谢，经过检查，是主服务器防火墙配置问题，重启后规则失效导致。
