### ISSUE TITLE
魔改版后端一直连接不上前端数据库

### ISSUE THREAD

**Issue by chocolatesir** [glzjin/ss-panel-v3-mod#321]
后端系统是debian7，安装的wiki上的魔改版后端，使用supervisor守护进程，启动后提示如下错误（服务端数据库账户已开启远程登录，且有全局权限）
7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '104.xxx.xxx.xxx' (110)")

2016-10-13 01:31:04 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2016-10-13 01:31:04 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-10-13 01:31:04 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-10-13 01:31:23 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2016-10-13 01:31:23 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-10-13 01:31:23 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-10-13 01:32:26 ERROR    db_transfer.py:561 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 553, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '104.xxx.xxx.xxx' (110)")

2016-10-13 01:33:26 ERROR    auto_block.py:185 Auto block thread error
2016-10-13 01:34:29 ERROR    db_transfer.py:561 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 553, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '104.xxx.xxx.xxx' (110)")

**Comment by glzjin** [comment]
请检查下数据库服务器3306端口是否开放。

**Comment by chocolatesir** [comment]
3306是开启的，在探针上检测了没问题。

**Comment by JohnFreeman9** [comment]
@chocolatesir 请确认前后端的3306都开

**Comment by chocolatesir** [comment]
debian7没有开启防火墙啊。。

**Comment by glzjin** [comment]
@JohnFreeman9 后端能正常telnet通数据库服务器3306即可

**Comment by glzjin** [comment]
@chocolatesir 不要在探针上检测

**Comment by chocolatesir** [comment]
确实。。。探针检测的不对。数据库服务端放行端口后连接正常，感谢。
