### ISSUE TITLE
后端启用SSL以 加密数据库与服务端的连接，报错，怎么办？？

### ISSUE THREAD

**Issue by mabangbang** [glzjin/ss-panel-v3-mod#335]
执行python server.py进行纠错，查看报错的情况如下：
loaded collections.OrderedDict
IPv6 support
2016-10-17 20:44:42 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-10-17 20:44:42 INFO     asyncdns.py:324 dns server: [('10.15.0.1', 53), ('158.205.237.131', 53), ('158.205.229.244', 53)]
2016-10-17 20:44:42 INFO     asyncdns.py:324 dns server: [('10.15.0.1', 53), ('158.205.237.131', 53), ('158.205.229.244', 53)]
2016-10-17 20:44:42 ERROR    db_transfer.py:561 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 553, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 53, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8',ssl={'ca':get_config().MYSQL_SSL_CA,'cert':get_config().MYSQL_SSL_CERT,'key':get_config().MYSQL_SSL_KEY})
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 472, in _send_authentication
    ca_certs=self.ca)
  File "/usr/lib64/python2.6/ssl.py", line 342, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs)
  File "/usr/lib64/python2.6/ssl.py", line 120, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.6/ssl.py", line 279, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:492: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

**Comment by glzjin** [comment]
链路问题= =自己想办法
