### ISSUE TITLE
后端内存占用过高

### ISSUE THREAD

**Issue by wabcwell** [glzjin/ss-panel-v3-mod#366]
服务器安装了锐速。
然后就安装了SSR（赵老板的修改版）的后端。
然后内存占用的太厉害，经常被kill
![qq 20161027143745](https://cloud.githubusercontent.com/assets/1608855/19757001/fb330414-9c52-11e6-8178-c25a2ab55c92.jpg)

**Comment by wabcwell** [comment]
centos 6 X64 kvm

**Comment by glzjin** [comment]
@wabcwell 发下后端日志？

**Comment by wabcwell** [comment]
使用supervisord 可以启动后端。
使用logrun.sh启动不了日志如下
`[root@centos-512mb-sgp1-01 shadowsocks]# ./tail.sh
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 62, in __init__
    self.__recv_packet()
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 81, in __recv_packet
    packet_header = self.__recv_from_socket(4)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 72, in __recv_from_socket
    recv_data = self._socket.recv(size)
timeout: timed out

2016-10-27 07:03:17 INFO     auto_block.py:59 Read hosts.deny from line 1557
2016-10-27 07:04:35 INFO     auto_block.py:59 Read hosts.deny from line 1559
2016-10-27 07:05:21 ERROR    db_transfer.py:561 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 553, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 411, in _connect
    self._get_server_information()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 512, in _get_server_information
    packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 62, in __init__
    self.__recv_packet()
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 81, in __recv_packet
    packet_header = self.__recv_from_socket(4)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 72, in __recv_from_socket
    recv_data = self._socket.recv(size)
timeout: timed out
`

**Comment by wabcwell** [comment]
日志都是些这种东西
2016-10-27 07:45:08 INFO     db_transfer.py:495 db start server at port [16645] pass [****] protocol [auth_sha1_v2_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-10-27 07:45:08 INFO     server_pool.py:138 starting server at [::]:16645
2016-10-27 07:45:08 INFO     server_pool.py:164 starting server at 0.0.0.0:16645
2016-10-27 07:45:08 INFO     db_transfer.py:495 db start server at port [50697] pass [****] protocol [auth_sha1_v2_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-10-27 07:45:08 INFO     server_pool.py:138 starting server at [::]:50697
2016-10-27 07:45:08 INFO     server_pool.py:164 starting server at 0.0.0.0:50697
2016-10-27 07:45:08 INFO     db_transfer.py:495 db start server at port [22744] pass [****] protocol [auth_sha1_v2_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-10-27 07:45:08 INFO     server_pool.py:138 starting server at [::]:22744
2016-10-27 07:45:08 INFO     server_pool.py:164 starting server at 0.0.0.0:22744
2016-10-27 07:45:08 INFO     db_transfer.py:495 db start server at port [18407] pass [****] protocol [auth_sha1_v2_compatible] obfs [tls1.2_ticket_auth_compatible]
2016-10-27 07:45:08 INFO     server_pool.py:138 starting server at [::]:18407
2016-10-27 07:45:08 INFO     server_pool.py:164 starting server at 0.0.0.0:18407
