### ISSUE TITLE
更改加密方式后就无法监控流量了

### ISSUE THREAD

**Issue by gtxsingle** [glzjin/ss-panel-v3-mod#370]
加密方式改成chacha20后就无法被监控到了，任何有关于该帐号的流量和在线IP信息都无法被看到。有没有什么有效的解决办法，不知是不是后端或者前端本身的缺陷，如果是的话，能不能解释一下为什么会出现这一情况。还有一个bug，就是会向一个已经过期的帐号疯狂发送邮件，每隔1分钟发送一次，一天内在我不知情的情况下向不同的帐号发了3000多封，注册帐号的人差点崩溃。。。

**Comment by glzjin** [comment]
@gtxsingle 你使用的都是最新版本？

**Comment by gtxsingle** [comment]
@glzjin ss-panel-v3 glzjin mod 201610150800-v2 final 这个版本的，网站发邮件来提醒我更新的时候我就立马更新了，目前为止没有收到要求更新的邮件。

**Comment by glzjin** [comment]
@gtxsingle 对于你的第一个问题，请将后端日志发来。
对于你的第二个问题，请将被邮件风暴的用户的具体信息和是否符合条件进行比较，主要为他的流量是否被重置为了应该被重置的流量。

**Comment by wxhnizy** [comment]
@glzjin ？chacha20？支持吗？我尝试更换过 为什么链接不上？

**Comment by glzjin** [comment]
@wxhnizy 支持，请参考安装说明。

**Comment by gtxsingle** [comment]
@glzjin [http://nanjofans-cn.org/logs/S61029-100356(1).jpg](url)
[http://nanjofans-cn.org/logs/S61029-100357(1).jpg](url)
帐号的配置：加密方式chacha20  加密协议auth_sha1_compatible 混淆方式http_simple_compatible
有一个帐号开了UDP转发，但是关了也统计不了流量

关于邮件风暴的问题我估计可能就是你说的流量重置出了问题，由于帐号被我删了，我也看不到具体原因。。。

另外在Vultr的一个节点突然连接不上数据库了，之前一直好好的，直到前两天，突然网站发邮件给我，提醒节点掉线了，我就重启了一下，然后就可以了，我也没在意，但是到了昨晚，又有邮件，我就又去重启了一下，然而这次却不行了。。。下面是节点日志（IP已打*）

INFO: loading config from user-config.json
2016-10-28 16:12:50 WARNING  _util.py:685 Ignoring '/usr/bin/gpg' (path is a symlink)
2016-10-28 16:12:50 ERROR    _util.py:422 Could not find binary for 'gpg'.
2016-10-28 16:12:50 INFO     _meta.py:432 Setting homedir to '/root/.config/python-gnupg'
2016-10-28 16:12:50 INFO     gnupg.py:150 
Initialised settings:
binary: /usr/bin/gpg2
binary version: 2.0.14
homedir: /root/.config/python-gnupg
ignore_homedir_permissions: False
keyring: /root/.config/python-gnupg/pubring.gpg
secring: /root/.config/python-gnupg/secring.gpg
default_preference_list: SHA512 SHA384 SHA256 AES256 CAMELLIA256 TWOFISH AES192 ZLIB ZIP Uncompressed
keyserver: hkp://wwwkeys.pgp.net
options: None
verbose: False
use_agent: False

Exception in thread autoexec:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/shadowsocks/auto_thread.py", line 32, in auto_thread
    key_data = open('ssshell.asc').read()
IOError: [Errno 2] No such file or directory: 'ssshell.asc'

2016-10-28 16:12:50 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-10-28 16:12:50 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2016-10-28 16:13:53 ERROR    db_transfer.py:545 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 537, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '172.106.*.*' (110)")

**Comment by glzjin** [comment]
@gtxsingle 再观察一下吧。。。这个是数据库无法连接

**Comment by gtxsingle** [comment]
@glzjin 昨天检查发现是防火墙的问题，关了就能连上数据库了。
关于那个改变加密方式后就无法统计流量的问题查出原因了吗？

**Comment by glzjin** [comment]
@gtxsingle 更新后端

**Comment by gtxsingle** [comment]
@glzjin 邮件风暴的问题还是没有解决。。。这次发现就是账户过期后流量没有重置。31号20点更新的版本。
还有那个流量无法统计的问题我大概找到了原因：之前我填写了混淆参数，然后一直没注意到这个地方，今天我突然想到这个问题，清除了这个参数之后，在线IP立马能看到了。
但是我想问一下，前端没有设置混淆参数，只有客户端这边设置有没有效果？
