### ISSUE TITLE
auto_block是不是就是把用户踢下线？

### ISSUE THREAD

**Issue by tsongneil** [glzjin/ss-panel-v3-mod#385]
2016-10-31 05:33:19 INFO     auto_block.py:59 Read hosts.deny from line 91616
2016-10-31 05:34:20 INFO     auto_block.py:59 Read hosts.deny from line 91618
2016-10-31 05:35:22 INFO     auto_block.py:59 Read hosts.deny from line 91620
2016-10-31 05:36:24 INFO     auto_block.py:59 Read hosts.deny from line 91622
2016-10-31 05:37:25 INFO     auto_block.py:59 Read hosts.deny from line 91624

赵大 用户掉线是因为这个么-.-

**Comment by glzjin** [comment]
@tsongneil 不是

**Comment by tsongneil** [comment]
好的 谢谢赵大   那请问下  新更新的后端  单端口多用户  改的那个  zhaojin:80  我不用单端口多用户是不是不需要改

**Comment by tsongneil** [comment]
Exception in thread speedtest:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/shadowsocks/speedtest_thread.py", line 124, in speedtest_thread
    time.sleep(hour * 3600)
TypeError: a float is required

另外日志经常出现这个  好像和测速相关  要紧么
