### ISSUE TITLE
运行python server.py报错，但是前端后端放一个vps就没报错！后端到前端3306一直CLOSE！

### ISSUE THREAD

**Issue by ss6916** [glzjin/ss-panel-v3-mod#409]
[root@skybbk shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
2016-11-07 09:19:36 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-11-07 09:19:36 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-07 09:19:36 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-07 09:19:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:19:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:19:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:19:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:19:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:20:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:20:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:20:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:20:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:20:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:20:37 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:21:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:21:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:21:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:21:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:21:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:21:37 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:22:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:22:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:22:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:22:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:22:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:22:37 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:23:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:23:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:23:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:23:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:23:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:23:38 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:24:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:24:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:24:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:24:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:24:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:24:38 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:25:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:25:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:25:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:25:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:25:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:25:38 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:26:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:26:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:26:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:26:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:26:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:26:39 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:27:36 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:27:36 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:27:36 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:27:36 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:27:36 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:27:39 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:28:37 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:28:37 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:28:37 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:28:37 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:28:37 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:28:39 ERROR    auto_block.py:185 Auto block thread error
2016-11-07 09:29:37 ERROR    db_transfer.py:60 (1045, u"Access denied for user 'root'@'27.122.57.205' (using password: YES)")
2016-11-07 09:29:37 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-07 09:29:37 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-07 09:29:37 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-07 09:29:37 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-07 09:29:39 ERROR    auto_block.py:185 Auto block thread error

**Comment by bluekk935** [comment]
前端防火墙清楚下规则试试?

**Comment by ss6916** [comment]
@bluekk935 前端防火墙直接关了 探针测试和站长扫描3306是对外开放的

**Comment by a86913179** [comment]
确定mysql账户设置任意主机了？而不是只有localhost和127.0.0.1
