### ISSUE TITLE
后端偶现错误

### ISSUE THREAD

**Issue by Woophp** [glzjin/ss-panel-v3-mod#419]
2016-11-12 17:33:13 WARNING  common.py:304 You did't specify CIDR routing prefix size for 210.244.71.25, implicit treated as 210.244.71.25/32

2016-11-12 17:33:13 WARNING  common.py:304 You did't specify CIDR routing prefix size for 210.244.71.25, implicit treated as 210.244.71.25/32

2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:80 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:102 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:112 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:122 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:132 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:145 local variable 'conn' referenced before assignment
2016-11-12 17:35:43 ERROR    db_transfer.py:600 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 588, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 266, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 223, in update_all_user
    conn.close()
UnboundLocalError: local variable 'conn' referenced before assignment

2016-11-12 17:35:48 ERROR    auto_block.py:185 Auto block thread error

**Comment by glzjin** [comment]
@Woophp 升级。

**Comment by glzjin** [comment]
@Woophp 再更新下即可
