### ISSUE TITLE
后端报错：local variable 'sock' referenced before assignment

### ISSUE THREAD

**Issue by Woophp** [glzjin/ss-panel-v3-mod#433]
2016-11-16 10:27:54 ERROR    tcprelay.py:1044 [Errno 32] Broken pipe
2016-11-16 10:27:54 ERROR    tcprelay.py:1045 exception from ::ffff:117.136.12.108:27431
2016-11-16 10:28:26 INFO     auto_block.py:59 Read hosts.deny from line 32085
2016-11-16 10:28:56 WARNING  common.py:304 You did't specify CIDR routing prefix size for 210.244.71.25, implicit treated as 210.244.71.25/32
2016-11-16 10:28:56 WARNING  common.py:304 You did't specify CIDR routing prefix size for 210.244.71.25, implicit treated as 210.244.71.25/32
2016-11-16 10:29:46 ERROR    auto_block.py:185 Auto block thread error
2016-11-16 10:30:16 ERROR    db_transfer.py:540 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 532, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 210, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 55, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 405, in _connect
    sock.close()
UnboundLocalError: local variable 'sock' referenced before assignment

**Comment by glzjin** [comment]
@Woophp 你用的后端的版本是哪时候更新的？

**Comment by Woophp** [comment]
@glzjin   最新的，只有一个节点会，很奇怪，我现在重装系统测试
