### ISSUE TITLE
后端错误

### ISSUE THREAD

**Issue by Woophp** [glzjin/ss-panel-v3-mod#456]
2016-11-24 16:11:04 INFO     auto_block.py:59 Read hosts.deny from line 21795
2016-11-24 16:11:09 ERROR    db_transfer.py:540 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 532, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 210, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 70, in update_all_user
    cur.execute("INSERT INTO `user_traffic_log` (`id`, `user_id`, `u`, `d`, `Node_ID`, `rate`, `traffic`, `log_time`) VALUES (NULL, '" + str(self.port_uid_table[id]) + "', '" + str(dt_transfer[id][0]) +"', '" + str(dt_transfer[id][1]) + "', '" + str(get_config().NODE_ID) + "', '" + str(self.traffic_rate) + "', '" + self.trafficShow((dt_transfer[id][0]+dt_transfer[id][1]) * self.traffic_rate) + "', unix_timestamp()); ")
KeyError: 17330L

**Comment by glzjin** [comment]
@Woophp 你就不能发全吗？

**Comment by glzjin** [comment]
以后有问题请发到后端的issue
