### ISSUE TITLE
新节点，运行调试模式出现错误

### ISSUE THREAD

**Issue by e8732** [glzjin/ss-panel-v3-mod#459]
运行python server.py，先出现如下提示，客户端无法翻墙。
`2016-11-25 12:50:56 WARNING  _util.py:685 Ignoring '/usr/bin/gpg' (path is a symlink)
2016-11-25 12:50:56 ERROR    _util.py:422 Could not find binary for 'gpg'.
2016-11-25 12:50:56 INFO     _meta.py:432 Setting homedir to '/root/.config/python-gnupg'
2016-11-25 12:50:56 INFO     gnupg.py:150
Initialised settings:
binary: /usr/bin/gpg2
binary version: 2.0.22
homedir: /root/.config/python-gnupg
ignore_homedir_permissions: False
keyring: /root/.config/python-gnupg/pubring.gpg
secring: /root/.config/python-gnupg/secring.gpg
default_preference_list: SHA512 SHA384 SHA256 AES256 CAMELLIA256 TWOFISH AES192 ZLIB ZIP Uncompressed
keyserver: hkp://wwwkeys.pgp.net
options: None
verbose: False
use_agent: False

Exception in thread autoexec:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/libsodium-1.0.10/shadowsocks/auto_thread.py", line 32, in auto_thread
    key_data = open('ssshell.asc').read()
IOError: [Errno 2] No such file or directory: 'ssshell.asc'
`

https://www.guga.ga

**Comment by glzjin** [comment]
把自动执行关掉就好。
