### ISSUE TITLE
SS服务端无法远程访问数据库启动SS

### ISSUE THREAD

**Issue by YueYueYue** [glzjin/ss-panel-v3-mod#462]
赵老师您好。鄙人的一个多节点小站，近来发现一个问题。其中一个节点（VPS）正常安装python、cymysql、您的魔改版SSR后，启动server.py出现以下报错：
2016-11-27 08:41:49 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2016-11-27 08:41:49 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-27 08:41:49 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-27 08:42:49 INFO     auto_block.py:59 Read hosts.deny from line 17
2016-11-27 08:42:50 ERROR    db_transfer.py:542 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 535, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 255, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) +" "+node_group_sql+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

问题就在于相同的配置文件（userapiconfig.py）只是node id不同而已，其他所有节点都能正常启动，就这个节点不行。查看了该节点的iptables都没有阻挡。我重新安装了VPS的OS，还是一样的问题出现。SS服务端是最新从github下载的。

您能帮忙看看是哪里不对吗？谢谢。

**Comment by glzjin** [comment]
@YueYueYue 网络问题

**Comment by YueYueYue** [comment]
谢谢您的回复。这个网络问题可能是什么原因造成的呢？是因为节点和数据库所在VPS之间的网络有问题吗？我尝试在有问题的这个节点安装了mysql，然后远程访问站点的数据库是没问题的。我目前使用的是ubuntu系统，如果我换成其他系统比如debian或者centos，是否能解决问题呢？

谢谢！

**Comment by glzjin** [comment]
@YueYueYue 不能

**Comment by a86913179** [comment]
time out，自己ping一下前端IP，不行就删VPS
