### ISSUE TITLE
赵大用您的后端报错

### ISSUE THREAD

**Issue by ztutu** [glzjin/ss-panel-v3-mod#506]
站点s.ztutu.com
前端搭建好了，节点显示ok。userapiconfig.py里面就改了节点编号和数据库信息。运行python server.py报错如下。
Last login: Fri Dec 23 18:11:08 2016 from 117.136.67.148
root@zhanggaoxiang:~# cd ssr/shadowsocks/
root@zhanggaoxiang:~/ssr/shadowsocks# python server.py
loaded collections.OrderedDict
IPv6 support
2016-12-23 18:18:51 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2016-12-23 18:18:51 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53), ('4.2.2.1', 53), ('4.2.2.2', 53)]
2016-12-23 18:18:51 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53), ('4.2.2.1', 53), ('4.2.2.2', 53)]
2016-12-23 18:18:51 ERROR    db_transfer.py:548 Traceback (most recent call last):
  File "/root/ssr/shadowsocks/db_transfer.py", line 541, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/ssr/shadowsocks/db_transfer.py", line 236, in pull_db_all_user
    cur.execute("SELECT `node_group`,`node_class`,`node_speedlimit`,`traffic_rate`,`mu_only` FROM ss_node where `id`='" + str(get_config().NODE_ID) + "' AND (`node_bandwidth`<`node_bandwidth_limit` OR `node_bandwidth_limit`=0)")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'mu_only' in 'field list'")

^CTraceback (most recent call last):
  File "server.py", line 68, in main
    time.sleep(10)
KeyboardInterrupt
2016-12-23 18:19:52 INFO     auto_block.py:59 Read hosts.deny from line 570
2016-12-23 18:20:52 INFO     auto_block.py:59 Read hosts.deny from line 572
2016-12-23 18:21:52 INFO     auto_block.py:59 Read hosts.deny from line 574
2016-12-23 18:22:52 INFO     auto_block.py:59 Read hosts.deny from line 576
2016-12-23 18:23:52 INFO     auto_block.py:59 Read hosts.deny from line 578

**Comment by HanC890** [comment]
你的前端需要更新并且你的数据库需要导入"glzjin_28.sql"这个文件
