### ISSUE TITLE
后端链接数据库报错

### ISSUE THREAD

**Issue by A1exLiu** [glzjin/ss-panel-v3-mod#509]
一直都是按照同一个方法配置的，但是今天新节点突然出了问题，python报错如下：
[root@localhost shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
2016-12-25 00:12:56 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-12-25 00:12:56 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-12-25 00:12:56 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-12-25 00:12:56 ERROR    db_transfer.py:548 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 541, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 236, in pull_db_all_user
    cur.execute("SELECT `node_group`,`node_class`,`node_speedlimit`,`traffic_rate`,`mu_only` FROM ss_node where `id`='" + str(get_config().NODE_ID) + "' AND (`node_bandwidth`<`node_bandwidth_limit` OR `node_bandwidth_limit`=0)")
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'mu_only' in 'field list'")

^Z
[1]+  Stopped                 python server.py

烦劳各位dalao帮忙看下，十分感谢

**Comment by lithromantic** [comment]
导入28.sql
